# perfil usando como banco o H2
spring:
  sql:
    init:
      platform: h2
  datasource:
    url: jdbc:h2:mem:moviesDB
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    defer-datasource-initialization: true
  h2:
    console:
      enabled: true
      path: /h2-console
