# perfil usando como banco o MySQL
spring:
  datasource:
    url: jdbc:mysql://localhost:3307/bolsaSpring
    password: root
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true